### ISSUE TITLE
Frontend de apólices

### ISSUE THREAD

**Issue by hqnicolas** [hqnicolas/bd2#11]
@f2004felipe  Crie o front-end para manipular suas respectivas funcionalidades:
- `/purchase-policy`: Formulário para comprar uma apólice de seguro. @f2004felipe 
- `/manage-policies`: Página para visualizar e gerenciar apólices. @f2004felipe

**Comment by f2004felipe** [comment]
adicionados na pasta public, manage-policies.html e purchase-policy.html
