### ISSUE TITLE
Frontend de estoque 

### ISSUE THREAD

**Issue by hqnicolas** [hqnicolas/bd2#12]
@evandroluizrd  Crie o front-end para manipular suas respectivas funcionalidades:
- `/register-claim`: Formulário para registrar uma reivindicação.  @evandroluizrd
- `/evaluate-claim`: Página de administração para avaliar reivindicações.  @evandroluizrd
- `/manage-inventory`: Página de administração para gerenciar inventário. @evandroluizrd
- `/risk-analysis`: Página de administração para análise de risco e ajustes de apólice. @evandroluizrd

**Comment by evandroluizrd** [comment]
Feito
