### ISSUE TITLE
Criação do diagrama do banco de dados (modelo Físico)

### ISSUE THREAD

**Issue by hqnicolas** [hqnicolas/bd2#3]
@evandroluizrd com base no modelo da empresa apresentado pela @bfontanayasmin,  Crie o diagrama de modelo físico em uma plataforma online. para anexarmos neste projeto

**Comment by evandroluizrd** [comment]
![Modelo Fisico](https://github.com/user-attachments/assets/029ee14f-ad71-4f57-ac3b-22e2ec3c1abb)
