### ISSUE TITLE
Preenchimento dos dados do banco para rodar o CRUD

### ISSUE THREAD

**Issue by hqnicolas** [hqnicolas/bd2#5]
@evandroluizrd  Crie o DML para preencher o banco de dados definido pelo @TonClei91
estes dados são necessários para inicializar a aplicação como "email do admin"
armazenar estes arquivos em /src/scripts/dml.sql

**Comment by evandroluizrd** [comment]
![Modelo Fisico](https://github.com/user-attachments/assets/688c552a-54bc-4031-9e39-ebfa2bfd001f)
