### ISSUE TITLE
Aumentem o desempenho do banco!

### ISSUE THREAD

**Issue by hqnicolas** [hqnicolas/bd2#6]
@Axelfilastro Aplique técnicas para melhoria do desempenho do banco de dados, um exemplo é aplicação de indices para as tabelas.

você deve adicionar estes scripts na pasta:  /src/scripts

**Comment by Axelfilastro** [comment]
-- Tabela: clients
CREATE TABLE IF NOT EXISTS  clients (id SERIAL PRIMARY KEY, nome VARCHAR(255) NOT NULL, cpf VARCHAR(255) UNIQUE NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, telefone VARCHAR(255), endereco VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- Tabela: celulares
CREATE TABLE IF NOT EXISTS  celulares (id SERIAL PRIMARY KEY, modelo VARCHAR(255) NOT NULL, imei VARCHAR(255) UNIQUE NOT NULL, valor DECIMAL(10, 2) NOT NULL, cliente_id INTEGER REFERENCES clients(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- Tabela: apolices
CREATE TABLE IF NOT EXISTS  apolices (id SERIAL PRIMARY KEY, numero VARCHAR(100) UNIQUE NOT NULL, data_emissao TIMESTAMP NOT NULL, data_validade TIMESTAMP NOT NULL, cobertura VARCHAR(255) NOT NULL, premio DECIMAL(10, 2) NOT NULL, cliente_id INTEGER REFERENCES clients(id), celular_id INTEGER REFERENCES celulares(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

-- Tabela: sinistros
CREATE TABLE IF NOT EXISTS  sinistros (id SERIAL PRIMARY KEY, data_registro TIMESTAMP NOT NULL, descricao TEXT NOT NULL, status VARCHAR(50) NOT NULL, valor_indenizacao DECIMAL(10, 2), apolice_id INTEGER REFERENCES apolices(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

-- Tabela: estoque_pecas
CREATE TABLE IF NOT EXISTS  estoque_pecas (id SERIAL PRIMARY KEY, nome_peca VARCHAR(255) NOT NULL, quantidade INTEGER NOT NULL, level_critico INTEGER NOT NULL, valor_unitario DECIMAL(10, 2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- Tabela: entradas_pecas
CREATE TABLE IF NOT EXISTS  entradas_pecas (id SERIAL PRIMARY KEY, data_entrada TIMESTAMP NOT NULL, quantidade INTEGER NOT NULL, estoque_peca_id INTEGER REFERENCES estoque_pecas(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

-- Tabela: saidas_pecas
CREATE TABLE IF NOT EXISTS  saidas_pecas (id SERIAL PRIMARY KEY, data_saida TIMESTAMP NOT NULL, quantidade INTEGER NOT NULL, estoque_peca_id INTEGER REFERENCES estoque_pecas(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- Tabela: riscos
CREATE TABLE IF NOT EXISTS  riscos (id SERIAL PRIMARY KEY, tipo_risco VARCHAR(255) NOT NULL, taxa_sinistro DECIMAL(10, 2) NOT NULL, cobertura_recomendada VARCHAR(255) NOT NULL, premio_recomendado DECIMAL(10, 2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- Tabela: metadata
CREATE TABLE IF NOT EXISTS  metadata (initialized BOOLEAN DEFAULT FALSE);

**Comment by Axelfilastro** [comment]
-- Índices: Crie índices para otimização de desempenho

-- Crie índice na coluna imei para pesquisas mais rápidas na tabela Celulares
CREATE INDEX IF NOT EXISTS idx_imei ON Celulares (imei);

-- Crie um índice na coluna cliente_id para pesquisas mais rápidas na tabela Celulares
CREATE INDEX IF NOT EXISTS idx_cliente_id ON Celulares (cliente_id);

-- Crie um índice na coluna apolice_id para pesquisas mais rápidas na tabela Sinistros
CREATE INDEX IF NOT EXISTS idx_apolice_id ON Sinistros (apolice_id);

-- Criar índice na coluna estoque_peca_id para consultas mais rápidas na tabela entradas_pecas
CREATE INDEX IF NOT EXISTS idx_entradas_peças_estoque_peca_id ON entradas_pecas (estoque_peca_id);

-- Criar índice na coluna estoque_peca_id para consultas mais rápidas na tabela saidas_pecas
CREATE INDEX IF NOT EXISTS idx_saidas_pecas_estoque_peca_id ON saidas_pecas (estoque_peca_id);

-- Index aplicado em clients.email
CREATE INDEX IF NOT EXISTS idx_clients_email ON clients(email);

-- Index aplicado em apolices.numero
CREATE INDEX IF NOT EXISTS idx_apolices_numero ON apolices(numero);

-- Index aplicado em apolices.cliente_id
CREATE INDEX IF NOT EXISTS idx_apolices_cliente_id ON apolices(cliente_id);

-- Index aplicado em apolices.celular_id
CREATE INDEX IF NOT EXISTS idx_apolices_celular_id ON apolices(celular_id);

-- Index aplicado em sinistros.apolice_id
CREATE INDEX IF NOT EXISTS idx_sinistros_apolice_id ON sinistros(apolice_id);

-- Index aplicado em entradas_pecas.estoque_peca_id
CREATE INDEX IF NOT EXISTS idx_entradas_pecas_estoque_peca_id ON entradas_pecas(estoque_peca_id);
