### ISSUE TITLE
Frontend de Usuário

### ISSUE THREAD

**Issue by hqnicolas** [hqnicolas/bd2#9]
@Axelfilastro  Crie o front-end para manipular suas respectivas funcionalidades:
- `/register`: formulário de registro do usuário. @Axelfilastro 
- `/login`: formulário de login do usuário. @Axelfilastro

**Comment by Axelfilastro** [comment]
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciamento de Perfil</title>
    <link rel="stylesheet" href="estiloperfil.css">
</head>
<body>
    <div class="container">
        <h1>Registrar</h1>
        <form id="profileForm">
            
            <label for="name">Nome:</label>
            <input type="text" id="nome" name="nome" required placeholder="Digite seu nome completo">

            
            <label for="cpf">CPF:</label>
            <input type="text" id="cpf" name="cpf" required min="11" placeholder="Digite seu CPF">

            
            <label for="telefone">Número de Telefone:</label>
            <input type="tel" id="telefone" name="telefone" required placeholder="Ex: (11) 98765-4321">

            
            <fieldset>
                <legend>Endereço</legend>
                <label for="street">Rua:</label>
                <input type="text" id="street" name="street" required placeholder="Digite sua rua">

                <label for="number">Número:</label>
                <input type="text" id="number" name="number" required placeholder="Digite o número">

                <label for="complement">Complemento:</label>
                <input type="text" id="complement" name="complement" placeholder="Digite o complemento (opcional)">

                <label for="cep">CEP:</label>
                <input type="text" id="cep" name="cep" required placeholder="Digite o CEP">

                <label for="neighborhood">Bairro:</label>
                <input type="text" id="neighborhood" name="neighborhood" required placeholder="Digite o bairro">

                <label for="city">Cidade:</label>
                <input type="text" id="city" name="city" required placeholder="Digite a cidade">

                <label for="state">Estado:</label>
                <select id="state" name="state" required>
                    <option value="" disabled selected>Selecione o estado</option>
                    <option value="AC">Acre</option>
                    <option value="AL">Alagoas</option>
                    <option value="AP">Amapá</option>
                    <option value="AM">Amazonas</option>
                    <option value="BA">Bahia</option>
                    <option value="CE">Ceará</option>
                    <option value="DF">Distrito Federal</option>
                    <option value="ES">Espírito Santo</option>
                    <option value="GO">Goiás</option>
                    <option value="MA">Maranhão</option>
                    <option value="MT">Mato Grosso</option>
                    <option value="MS">Mato Grosso do Sul</option>
                    <option value="MG">Minas Gerais</option>
                    <option value="PA">Pará</option>
                    <option value="PB">Paraíba</option>
                    <option value="PR">Paraná</option>
                    <option value="PE">Pernambuco</option>
                    <option value="PI">Piauí</option>
                    <option value="RJ">Rio de Janeiro</option>
                    <option value="RN">Rio Grande do Norte</option>
                    <option value="RS">Rio Grande do Sul</option>
                    <option value="RO">Rondônia</option>
                    <option value="RR">Roraima</option>
                    <option value="SC">Santa Catarina</option>
                    <option value="SP">São Paulo</option>
                    <option value="SE">Sergipe</option>
                    <option value="TO">Tocantins</option>
                </select>
            </fieldset>

            
            <label for="email">E-mail:</label>
            <input type="email" id="email" name="email" required placeholder="Digite seu e-mail">

            
            <button type="submit">Cadastrar Cliente</button>
        </form>
        <div id="response"></div>
    </div>

    <script>
        document.getElementById('profileForm').addEventListener('submit', async (e) => {
            e.preventDefault();

            const profileData = {
                nome: document.getElementById('nome').value,
                cpf: document.getElementById('cpf').value,
                email: document.getElementById('email').value,
                telefone: document.getElementById('telefone').value,
                endereco: {
                    street: document.getElementById('street').value,
                    number: document.getElementById('number').value,
                    complement: document.getElementById('complement').value,
                    cep: document.getElementById('cep').value,
                    neighborhood: document.getElementById('neighborhood').value,
                    city: document.getElementById('city').value,
                    state: document.getElementById('state').value,
                }
            };

            try {
                const response = await fetch('/register', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(profileData),
                });

                const data = await response.json();
                const responseDiv = document.getElementById('response');

                if (response.ok) {
                    responseDiv.textContent = data.message;
                    responseDiv.style.color = 'green';
                    setTimeout(() => {
                        window.location.href = '/login';
                    }, 2000);
                } else {
                    responseDiv.textContent = data.error || 'Erro ao Cadastrar o perfil.';
                    responseDiv.style.color = 'red';
                }
            } catch (error) {
                console.error('Erro na requisição:', error);
            }
        });
    </script>
</body>
</html>

**Comment by Axelfilastro** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Login</h1>
    <form action="/login" method="POST">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Login</button>
    </form>
</body>
</html>

**Comment by Axelfilastro** [comment]
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciamento de Perfil</title>
    <link rel="stylesheet" href="estiloperfil.css">
</head>
<body>
    <div class="container">
        <h1>Registrar</h1>
        <form id="profileForm">
            
            <label for="name">Nome:</label>
            <input type="text" id="nome" name="nome" required placeholder="Digite seu nome completo">

>         
>         <label for="cpf">CPF:</label>
>         <input type="text" id="cpf" name="cpf" required min="11" placeholder="Digite seu CPF">
> 
>         
>         <label for="telefone">Número de Telefone:</label>
>         <input type="tel" id="telefone" name="telefone" required placeholder="Ex: (11) 98765-4321">
> 
>         
>         <fieldset>
>             <legend>Endereço</legend>
>             <label for="street">Rua:</label>
>             <input type="text" id="street" name="street" required placeholder="Digite sua rua">
> 
>             <label for="number">Número:</label>
>             <input type="text" id="number" name="number" required placeholder="Digite o número">
> 
>             <label for="complement">Complemento:</label>
>             <input type="text" id="complement" name="complement" placeholder="Digite o complemento (opcional)">
> 
>             <label for="cep">CEP:</label>
>             <input type="text" id="cep" name="cep" required placeholder="Digite o CEP">
> 
>             <label for="neighborhood">Bairro:</label>
>             <input type="text" id="neighborhood" name="neighborhood" required placeholder="Digite o bairro">
> 
>             <label for="city">Cidade:</label>
>             <input type="text" id="city" name="city" required placeholder="Digite a cidade">
> 
>             <label for="state">Estado:</label>
>             <select id="state" name="state" required>
>                 <option value="" disabled selected>Selecione o estado</option>
>                 <option value="AC">Acre</option>
>                 <option value="AL">Alagoas</option>
>                 <option value="AP">Amapá</option>
>                 <option value="AM">Amazonas</option>
>                 <option value="BA">Bahia</option>
>                 <option value="CE">Ceará</option>
>                 <option value="DF">Distrito Federal</option>
>                 <option value="ES">Espírito Santo</option>
>                 <option value="GO">Goiás</option>
>                 <option value="MA">Maranhão</option>
>                 <option value="MT">Mato Grosso</option>
>                 <option value="MS">Mato Grosso do Sul</option>
>                 <option value="MG">Minas Gerais</option>
>                 <option value="PA">Pará</option>
>                 <option value="PB">Paraíba</option>
>                 <option value="PR">Paraná</option>
>                 <option value="PE">Pernambuco</option>
>                 <option value="PI">Piauí</option>
>                 <option value="RJ">Rio de Janeiro</option>
>                 <option value="RN">Rio Grande do Norte</option>
>                 <option value="RS">Rio Grande do Sul</option>
>                 <option value="RO">Rondônia</option>
>                 <option value="RR">Roraima</option>
>                 <option value="SC">Santa Catarina</option>
>                 <option value="SP">São Paulo</option>
>                 <option value="SE">Sergipe</option>
>                 <option value="TO">Tocantins</option>
>             </select>
>         </fieldset>
> 
>         
>         <label for="email">E-mail:</label>
>         <input type="email" id="email" name="email" required placeholder="Digite seu e-mail">
> 
>         
>         <button type="submit">Cadastrar Cliente</button>
>     </form>
>     <div id="response"></div>
> </div>
> 
> <script>
>     document.getElementById('profileForm').addEventListener('submit', async (e) => {
>         e.preventDefault();
> 
>         const profileData = {
>             nome: document.getElementById('nome').value,
>             cpf: document.getElementById('cpf').value,
>             email: document.getElementById('email').value,
>             telefone: document.getElementById('telefone').value,
>             endereco: {
>                 street: document.getElementById('street').value,
>                 number: document.getElementById('number').value,
>                 complement: document.getElementById('complement').value,
>                 cep: document.getElementById('cep').value,
>                 neighborhood: document.getElementById('neighborhood').value,
>                 city: document.getElementById('city').value,
>                 state: document.getElementById('state').value,
>             }
>         };
> 
>         try {
>             const response = await fetch('/register', {
>                 method: 'POST',
>                 headers: { 'Content-Type': 'application/json' },
>                 body: JSON.stringify(profileData),
>             });
> 
>             const data = await response.json();
>             const responseDiv = document.getElementById('response');
> 
>             if (response.ok) {
>                 responseDiv.textContent = data.message;
>                 responseDiv.style.color = 'green';
>                 setTimeout(() => {
>                     window.location.href = '/login';
>                 }, 2000);
>             } else {
>                 responseDiv.textContent = data.error || 'Erro ao Cadastrar o perfil.';
>                 responseDiv.style.color = 'red';
>             }
>         } catch (error) {
>             console.error('Erro na requisição:', error);
>         }
>     });
> </script>
</body>
</html>

**Comment by Axelfilastro** [comment]
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciamento de Perfil</title>
    <link rel="stylesheet" href="estiloperfil.css">
</head>
<body>
    <div class="container">
        <h1>Registrar</h1>
        <form id="profileForm">
            
            <label for="name">Nome:</label>
            <input type="text" id="nome" name="nome" required placeholder="Digite seu nome completo">

            
            <label for="cpf">CPF:</label>
            <input type="text" id="cpf" name="cpf" required min="11" placeholder="Digite seu CPF">

            
            <label for="telefone">Número de Telefone:</label>
            <input type="tel" id="telefone" name="telefone" required placeholder="Ex: (11) 98765-4321">

            
            <fieldset>
                <legend>Endereço</legend>
                <label for="street">Rua:</label>
                <input type="text" id="street" name="street" required placeholder="Digite sua rua">

                <label for="number">Número:</label>
                <input type="text" id="number" name="number" required placeholder="Digite o número">

                <label for="complement">Complemento:</label>
                <input type="text" id="complement" name="complement" placeholder="Digite o complemento (opcional)">

                <label for="cep">CEP:</label>
                <input type="text" id="cep" name="cep" required placeholder="Digite o CEP">

                <label for="neighborhood">Bairro:</label>
                <input type="text" id="neighborhood" name="neighborhood" required placeholder="Digite o bairro">

                <label for="city">Cidade:</label>
                <input type="text" id="city" name="city" required placeholder="Digite a cidade">

                <label for="state">Estado:</label>
                <select id="state" name="state" required>
                    <option value="" disabled selected>Selecione o estado</option>
                    <option value="AC">Acre</option>
                    <option value="AL">Alagoas</option>
                    <option value="AP">Amapá</option>
                    <option value="AM">Amazonas</option>
                    <option value="BA">Bahia</option>
                    <option value="CE">Ceará</option>
                    <option value="DF">Distrito Federal</option>
                    <option value="ES">Espírito Santo</option>
                    <option value="GO">Goiás</option>
                    <option value="MA">Maranhão</option>
                    <option value="MT">Mato Grosso</option>
                    <option value="MS">Mato Grosso do Sul</option>
                    <option value="MG">Minas Gerais</option>
                    <option value="PA">Pará</option>
                    <option value="PB">Paraíba</option>
                    <option value="PR">Paraná</option>
                    <option value="PE">Pernambuco</option>
                    <option value="PI">Piauí</option>
                    <option value="RJ">Rio de Janeiro</option>
                    <option value="RN">Rio Grande do Norte</option>
                    <option value="RS">Rio Grande do Sul</option>
                    <option value="RO">Rondônia</option>
                    <option value="RR">Roraima</option>
                    <option value="SC">Santa Catarina</option>
                    <option value="SP">São Paulo</option>
                    <option value="SE">Sergipe</option>
                    <option value="TO">Tocantins</option>
                </select>
            </fieldset>

            
            <label for="email">E-mail:</label>
            <input type="email" id="email" name="email" required placeholder="Digite seu e-mail">

            
            <button type="submit">Cadastrar Cliente</button>
        </form>
        <div id="response"></div>
    </div>

    <script>
        document.getElementById('profileForm').addEventListener('submit', async (e) => {
            e.preventDefault();

            const profileData = {
                nome: document.getElementById('nome').value,
                cpf: document.getElementById('cpf').value,
                email: document.getElementById('email').value,
                telefone: document.getElementById('telefone').value,
                endereco: {
                    street: document.getElementById('street').value,
                    number: document.getElementById('number').value,
                    complement: document.getElementById('complement').value,
                    cep: document.getElementById('cep').value,
                    neighborhood: document.getElementById('neighborhood').value,
                    city: document.getElementById('city').value,
                    state: document.getElementById('state').value,
                }
            };

            try {
                const response = await fetch('/register', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(profileData),
                });

                const data = await response.json();
                const responseDiv = document.getElementById('response');

                if (response.ok) {
                    responseDiv.textContent = data.message;
                    responseDiv.style.color = 'green';
                    setTimeout(() => {
                        window.location.href = '/login';
                    }, 2000);
                } else {
                    responseDiv.textContent = data.error || 'Erro ao Cadastrar o perfil.';
                    responseDiv.style.color = 'red';
                }
            } catch (error) {
                console.error('Erro na requisição:', error);
            }
        });
    </script>
</body>
</html>

**Comment by Axelfilastro** [comment]
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Login</h1>
    <form action="/login" method="POST">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Login</button>
    </form>
</body>
</html>

**Comment by Axelfilastro** [comment]
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciamento de Perfil</title>
    <link rel="stylesheet" href="estiloperfil.css">
</head>
<body>
    <div class="container">
        <h1>Registrar</h1>
        <form id="profileForm">
            
            <label for="name">Nome:</label>
            <input type="text" id="nome" name="nome" required placeholder="Digite seu nome completo">

            
            <label for="cpf">CPF:</label>
            <input type="text" id="cpf" name="cpf" required min="11" placeholder="Digite seu CPF">

            
            <label for="telefone">Número de Telefone:</label>
            <input type="tel" id="telefone" name="telefone" required placeholder="Ex: (11) 98765-4321">

            
            <fieldset>
                <legend>Endereço</legend>
                <label for="street">Rua:</label>
                <input type="text" id="street" name="street" required placeholder="Digite sua rua">

                <label for="number">Número:</label>
                <input type="text" id="number" name="number" required placeholder="Digite o número">

                <label for="complement">Complemento:</label>
                <input type="text" id="complement" name="complement" placeholder="Digite o complemento (opcional)">

                <label for="cep">CEP:</label>
                <input type="text" id="cep" name="cep" required placeholder="Digite o CEP">

                <label for="neighborhood">Bairro:</label>
                <input type="text" id="neighborhood" name="neighborhood" required placeholder="Digite o bairro">

                <label for="city">Cidade:</label>
                <input type="text" id="city" name="city" required placeholder="Digite a cidade">

                <label for="state">Estado:</label>
                <select id="state" name="state" required>
                    <option value="" disabled selected>Selecione o estado</option>
                    <option value="AC">Acre</option>
                    <option value="AL">Alagoas</option>
                    <option value="AP">Amapá</option>
                    <option value="AM">Amazonas</option>
                    <option value="BA">Bahia</option>
                    <option value="CE">Ceará</option>
                    <option value="DF">Distrito Federal</option>
                    <option value="ES">Espírito Santo</option>
                    <option value="GO">Goiás</option>
                    <option value="MA">Maranhão</option>
                    <option value="MT">Mato Grosso</option>
                    <option value="MS">Mato Grosso do Sul</option>
                    <option value="MG">Minas Gerais</option>
                    <option value="PA">Pará</option>
                    <option value="PB">Paraíba</option>
                    <option value="PR">Paraná</option>
                    <option value="PE">Pernambuco</option>
                    <option value="PI">Piauí</option>
                    <option value="RJ">Rio de Janeiro</option>
                    <option value="RN">Rio Grande do Norte</option>
                    <option value="RS">Rio Grande do Sul</option>
                    <option value="RO">Rondônia</option>
                    <option value="RR">Roraima</option>
                    <option value="SC">Santa Catarina</option>
                    <option value="SP">São Paulo</option>
                    <option value="SE">Sergipe</option>
                    <option value="TO">Tocantins</option>
                </select>
            </fieldset>

            
            <label for="email">E-mail:</label>
            <input type="email" id="email" name="email" required placeholder="Digite seu e-mail">

            
            <button type="submit">Cadastrar Cliente</button>
        </form>
        <div id="response"></div>
    </div>

    <script>
        document.getElementById('profileForm').addEventListener('submit', async (e) => {
            e.preventDefault();

            const profileData = {
                nome: document.getElementById('nome').value,
                cpf: document.getElementById('cpf').value,
                email: document.getElementById('email').value,
                telefone: document.getElementById('telefone').value,
                endereco: {
                    street: document.getElementById('street').value,
                    number: document.getElementById('number').value,
                    complement: document.getElementById('complement').value,
                    cep: document.getElementById('cep').value,
                    neighborhood: document.getElementById('neighborhood').value,
                    city: document.getElementById('city').value,
                    state: document.getElementById('state').value,
                }
            };

            try {
                const response = await fetch('/register', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(profileData),
                });

                const data = await response.json();
                const responseDiv = document.getElementById('response');

                if (response.ok) {
                    responseDiv.textContent = data.message;
                    responseDiv.style.color = 'green';
                    setTimeout(() => {
                        window.location.href = '/login';
                    }, 2000);
                } else {
                    responseDiv.textContent = data.error || 'Erro ao Cadastrar o perfil.';
                    responseDiv.style.color = 'red';
                }
            } catch (error) {
                console.error('Erro na requisição:', error);
            }
        });
    </script>
</body>
</html>

**Comment by Axelfilastro** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Login</h1>
    <form action="/login" method="POST">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Login</button>
    </form>
</body>
</html>
